name: futbolize
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Medium.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Italic.ttf
      - asset: assets/fonts/Roboto-MediumItalic.ttf
      - asset: assets/fonts/Roboto-BoldItalic.ttf
      - asset: assets/fonts/Roboto-Thin.ttf
      - asset: assets/fonts/Roboto-ThinItalic.ttf
      - asset: assets/fonts/Roboto-Light.ttf

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.png
    - assets/icons/left_boot.png
    - assets/icons/right_boot.png
    - assets/icons/messi.png